# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Cliente import download_pb2 as Cliente_dot_download__pb2


class DownloadStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.startDownload = channel.unary_unary(
                '/Download/startDownload',
                request_serializer=Cliente_dot_download__pb2.downloadRequest.SerializeToString,
                response_deserializer=Cliente_dot_download__pb2.downloadReply.FromString,
                )


class DownloadServicer(object):
    """Missing associated documentation comment in .proto file."""

    def startDownload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DownloadServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'startDownload': grpc.unary_unary_rpc_method_handler(
                    servicer.startDownload,
                    request_deserializer=Cliente_dot_download__pb2.downloadRequest.FromString,
                    response_serializer=Cliente_dot_download__pb2.downloadReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Download', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Download(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def startDownload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Download/startDownload',
            Cliente_dot_download__pb2.downloadRequest.SerializeToString,
            Cliente_dot_download__pb2.downloadReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
