# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\"9\n\x0f\x64ownloadRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\",\n\rdownloadReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t2M\n\x08\x44ownload\x12\x41\n\rstartDownload\x12\x17.search.downloadRequest\x1a\x15.search.downloadReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DOWNLOADREQUEST']._serialized_start=24
  _globals['_DOWNLOADREQUEST']._serialized_end=81
  _globals['_DOWNLOADREPLY']._serialized_start=83
  _globals['_DOWNLOADREPLY']._serialized_end=127
  _globals['_DOWNLOAD']._serialized_start=129
  _globals['_DOWNLOAD']._serialized_end=206
# @@protoc_insertion_point(module_scope)
